In [2]:
# student performance indicator

# life cycle of ML project

# 1. problem statement
## this project understands how the student's performance is affected by
# various factors such as Gender, Ethnicity, Parental level of education,
#  Lunch, Test preparation course, and scores in Math, Reading, and Writing.

# 2. data collection
## the data is collected from a CSV file named "StudentsPerformance.csv" which contains
#  information about students' performance in various subjects along with their demographic information.
# 8 cols and 1000 rows

In [3]:
# import data and libraries
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns
import numpy as np
import warnings
warnings.filterwarnings("ignore")

In [11]:
df = pd.read_csv(r'data\StudentsPerformance.csv')

In [12]:
df.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

In [13]:
# dataset info
'''
- gender : male or female
- race/ethnicity : group A, B, C, D, E
- parental level of education : some high school, high school, some college, associate's degree, bachelor's degree, master's degree

- lunch : standard or free/reduced
- test preparation course : none or completed before test
- math score : 0-100
- reading score : 0-100
- writing score : 0-100
'''

"\n- gender : male or female\n- race/ethnicity : group A, B, C, D, E\n- parental level of education : some high school, high school, some college, associate's degree, bachelor's degree, master's degree\n\n- lunch : standard or free/reduced\n- test preparation course : none or completed before test\n- math score : 0-100\n- reading score : 0-100\n- writing score : 0-100\n"

In [14]:
df.isna().sum()

gender                         0
race/ethnicity                 0
parental level of education    0
lunch                          0
test preparation course        0
math score                     0
reading score                  0
writing score                  0
dtype: int64

In [15]:
# check duplicates
df.duplicated().sum()

np.int64(0)

In [17]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   gender                       1000 non-null   str
 1   race/ethnicity               1000 non-null   str
 2   parental level of education  1000 non-null   str
 3   lunch                        1000 non-null   str
 4   test preparation course      1000 non-null   str
 5   math score                   1000 non-null   int64
 6   reading score                1000 non-null   int64
 7   writing score                1000 non-null   int64
dtypes: int64(3), str(5)
memory usage: 62.6 KB

In [18]:
# no of unique values in each column
df.nunique()

gender                          2
race/ethnicity                  5
parental level of education     6
lunch                           2
test preparation course         2
math score                     81
reading score                  72
writing score                  77
dtype: int64

In [19]:
# stats summary of numerical columns
df.describe()

       math score  reading score  writing score
count  1000.00000    1000.000000    1000.000000
mean     66.08900      69.169000      68.054000
std      15.16308      14.600192      15.195657
min       0.00000      17.000000      10.000000
25%      57.00000      59.000000      57.750000
50%      66.00000      70.000000      69.000000
75%      77.00000      79.000000      79.000000
max     100.00000     100.000000     100.000000

In [20]:
# exploring data
print('categories in gender:', df['gender'].nunique())
print('categories in race/ethnicity:', df['race/ethnicity'].nunique())
print('categories in parental level of education:', df['parental level of education'].nunique())
print('categories in lunch:', df['lunch'].nunique())
print('categories in test preparation course:', df['test preparation course'].nunique())

categories in gender: 2
categories in race/ethnicity: 5
categories in parental level of education: 6
categories in lunch: 2
categories in test preparation course: 2

In [21]:
# define numerical and categorical columns
numeric_features = [feature for feature in df.columns if df[feature].dtype != 'O']
categorical_features = [feature for feature in df.columns if df[feature].dtype == 'O']

# print cols
print('numerical features:', numeric_features)
print('categorical features:', categorical_features)

numerical features: ['gender', 'race/ethnicity', 'parental level of education', 'lunch', 'test preparation course', 'math score', 'reading score', 'writing score']
categorical features: []